name: gen:scaffold
description: Regenerate or update scaffolding based on specs
trigger: manual

action:
  type: message
  message: |
    Regenerate project scaffolding based on current specs in .kiro/specs/.

    Read:
    - .kiro/specs/app-spec.md
    - .kiro/specs/mcp-spec.md
    - .kiro/steering/coding-style.md

    Check for missing scaffolding in:
    - apps/api (Express + TypeScript backend)
    - apps/web (React + Vite frontend)
    - mcp-server (MCP tool server)

    Tasks:
    1. Verify directory structure matches specs
    2. Check for missing core files (package.json, tsconfig.json, entry points)
    3. Ensure type definitions match MCP tool schemas
    4. Verify stub implementations exist for all tools
    5. Check basic test file structure
    6. Validate spec compliance:
       - StackRequest type matches app-spec.md data model (language, framework, year, extras?)
       - StackResponse type matches app-spec.md (runtime_version, package_manager, packages, notes?)
       - StackPackage type includes name, version, category?, notes?, confidence?
       - MCP tool schema matches mcp-spec.md input/output schemas
       - Confidence scoring values (0.5 for fallback, 0.9 for accurate) are implemented
       - Haunted Mode logic checks confidence < 0.8 as per spec

    Propose any new files needed. Do not overwrite existing implementation logic, only update structure and types.

    Follow coding-style.md conventions.
